CREATE TABLE users 
(
    id_user INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    email VARCHAR(50) NOT NULL UNIQUE, 
    pass VARCHAR(255) NOT NULL, 
    is_admin BOOLEAN DEFAULT 0,
    lastname VARCHAR(100) NOT NULL,
    firstname VARCHAR(100) NOT NULL
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 ;