CREATE TABLE IF NOT EXISTS users 
(
    id_user INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    email VARCHAR(50) NOT NULL UNIQUE, 
    pass VARCHAR(255) NOT NULL, 
    is_admin BOOLEAN DEFAULT 0,
    lastname VARCHAR(100) NOT NULL,
    firstname VARCHAR(100) NOT NULL
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 ;


CREATE TABLE IF NOT EXISTS posts 
(
    id_post INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    id_user INT NOT NULL, 
    date_post DATETIME NOT NULL, 
    title VARCHAR(100) NOT NULL,
    content TEXT,
    img VARCHAR(250)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 ;